### ISSUE TITLE
Замечания по Triangle

### ISSUE THREAD

**Issue by AniSkyWorker** [JokerSSmile/MLiTA#1]
1. Во всех случаях, кроме как в функции OutputResultToFile используется make_pair для создания пары shortов

``` c++
previous = std::pair<short, short>((short)i, (short)k);
```

вместо этого можно либо использовать make_pair, либо предоставить возможность компилятору автоматически вызвать конструктор

``` c++
previous = { (short)i, (short)k };
```
1. В ManipulateWithMatrix в строчках вида 

``` c++
matrix[i][k].value = matrix[i][k].value + matrix[i - 1][k].value;
```

можно использовать += и не писать `matrix[i][k].value`
3. В ManipulateWithMatrix можно использовать в нескольких местах else if, чтобы убрать сильную вложенность условий

``` c++
            if (k == 0)
            {
                if (i > 1)
                {
                    matrix[i][k].value = matrix[i][k].value + matrix[i - 1][k].value;
                    matrix[i][k].previousCell = make_pair((short)i - 1, short(k));
                }
            }
            else
            {
                if (k == i)
                {
                    matrix[i][k].value = matrix[i][k].value + matrix[i - 1][k - 1].value;
                    matrix[i][k].previousCell = make_pair((short)i - 1, (short)k - 1);
                }
                else
                {
                    matrix[i][k].value = matrix[i][k].value + max(matrix[i - 1][k - 1].value, matrix[i - 1][k].value);
                    if (matrix[i - 1][k - 1].value > matrix[i - 1][k].value)
                    {
                        matrix[i][k].previousCell = make_pair((short)i - 1, (short)k - 1);
                    }
                    else
                    {
                        matrix[i][k].previousCell = make_pair((short)i - 1, (short)k);
                    }
                }
            }
```
1. ``` c++
   /////////////////////////// Debug tool //////////////////////////////////
   //void OutputMatrix(const vector<vector<Node>>& matrix, const unsigned& lineCount)
   //{
   //  for (size_t i = 0; i < lineCount + 1; i++)
   //  {
   //      for (size_t k = 0; k < i; k++)
   //      {
   //          cout << matrix[i][k].value << '\t';
   //      }
   //      cout << endl;
   //  }
   //}
   //////////////////////////////////////////////////////////////////////////
   ? - стоит убрать из итоговой версии, если программа работает правильно
   ```
2. убрать передачу в функции по константной ссылке простых типов, их быстрее будет передать по значению

``` c++
       const unsigned& lineCount
```

``` c++
       unsigned lineCount
```
1. по названиям функций в Triangle никак не понять, что происходит внутри, стоит переименовать
2. (опционально, рекомендуется) лучше завести класс, внутри которого будет храниться матрица и число линий, и все имеющиеся методы, чтобы постоянно не передавать ссылку, тогда можно оставить названия функций прежними, если название класса будет говорить за себя
3. логичнее будет делать push back, в вектор векторов, а не создавать квадратную матрицу, потому что остальные элементы все равно нигде не используются.
4. в функции main нигде не используемая переменная

``` c++
       unsigned inLinePos = 1;
```
1. непонятно зачем startMatrix - vector<Node> если от нее требуется хранить только числа исходного треугольника, с точки зрения экономии памяти и логики, проще, для инициализации рабочей матрицы, использовать цикл или работать с одной единственной матрицей, только в Node добавить еще одно поле, которое будет хранить исходные значения считанного треугольника
2. в функции ManipulateWithMatrix два раза ищется максимальный элемент, поместите увеличение значения matrix[i][k].value в проверку 

``` c++
                    matrix[i][k].value = matrix[i][k].value + max(matrix[i - 1][k - 1].value, matrix[i - 1][k].value);
                    if (matrix[i - 1][k - 1].value > matrix[i - 1][k].value)
                    {
                        matrix[i][k].previousCell = make_pair((short)i - 1, (short)k - 1);
                    }
                    else
                    {
                        matrix[i][k].previousCell = make_pair((short)i - 1, (short)k);
                    }
```

**Comment by sergey-shambir** [comment]
- в CalculatePathWithMaxWeight проверка `i > 0` бессмысленная, при i==0 цикл по k совершит 0 итераций
- ветка выполнения при `k == i` также бессмысленная, она недостижима
- закоментированный код в Triangle.cpp не нужен
- в папке `Triangle/Lab2_mlita/Debug` лежат посторонние файлы

**Comment by sergey-shambir** [comment]
Пока 4 из 5 из-за замечаний
